#controllers:
#    resource: ../src/Controller/
#    type: annotation

product_detail:
    path: /product/{id}
    controller: App\Product\Application\Controller\ProductController::detail

kernel:
    resource: ../src/Kernel.php
    type: annotation
